import React, { useState } from 'react'
import './Home.css'

function Home() {
    const [activeTab, setActiveTab] = useState('for you')
    function handleActiveTab(e) {
        setActiveTab(e.target.textContent.toLowerCase())
    }
    return (
        <div className="home">
            <div className="home__head">
                <header className="home__header">
                    <h1 className="home__title">Home</h1>
                </header>
                <div className="home__tabs">
                    <button className={activeTab === 'for you' ? 'home__tab-btn home__tab-btn--active' : "home__tab-btn"} onClick={handleActiveTab}>For You</button>
                    <button className={activeTab === 'following' ? 'home__tab-btn home__tab-btn--active' : "home__tab-btn"} onClick={handleActiveTab}>Following</button>
                </div>
            </div>
            <div className="home__body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, amet distinctio veniam, similique laboriosam totam facere quis debitis magnam dolores, numquam voluptatem possimus rem laudantium rerum nisi in non? Impedit neque nihil atque sapiente molestias qui dicta assumenda necessitatibus, iste officiis, sint, quos nisi esse? Sapiente, et natus incidunt explicabo, eveniet nesciunt exercitationem esse non velit magni dicta necessitatibus doloribus a facilis. Laborum, aliquam? Modi qui voluptatem iste minus, quas quae cupiditate recusandae aperiam, ut repellat ea at optio similique molestias quia. Amet ex debitis nulla doloribus quo animi adipisci aut tempora ratione ab. Quidem laborum at minima consequuntur delectus corrupti? Qui quaerat iure corrupti veniam ipsa neque nam unde incidunt, doloremque similique amet rem explicabo ullam, molestiae, doloribus ratione placeat at quae? Dicta quam tempora veniam aspernatur, temporibus illum esse, quo sint pariatur qui reprehenderit repellat optio, quaerat aliquam corporis? Ex officia, eius, minima vitae nam saepe dolorem impedit quod beatae error omnis exercitationem accusamus dignissimos quisquam quis commodi, qui voluptatibus alias deserunt! Quis, impedit qui molestias tempore perspiciatis harum dolorem officiis non eligendi recusandae autem, dolores iste quo. Esse quis eos cupiditate sunt, quaerat error pariatur nulla veniam ullam maiores laudantium possimus? Vel eveniet iste eos sequi tempore ad architecto nam dolore quae magnam, animi dolorum repudiandae, rem eligendi corporis harum voluptatem doloremque provident enim?
                    Aspernatur eligendi accusantium porro odio officia nam molestiae officiis autem quasi, aliquam iusto dolorem nihil dignissimos nobis ducimus earum cum. Quas, delectus? Odit veritatis placeat dolorem, aliquam, quasi debitis voluptatibus magnam nostrum ipsam rem quis dolores sunt. Tempore ad assumenda expedita adipisci? Facilis molestiae facere, eos vel sunt sint praesentium veritatis. Enim deleniti quidem ab quisquam autem dolor soluta assumenda in, reiciendis corrupti doloremque sequi perspiciatis nostrum voluptates neque velit, provident fugiat aliquid fugit quam officia quasi minima vitae? Tenetur, natus est. Deleniti?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, amet distinctio veniam, similique laboriosam totam facere quis debitis magnam dolores, numquam voluptatem possimus rem laudantium rerum nisi in non? Impedit neque nihil atque sapiente molestias qui dicta assumenda necessitatibus, iste officiis, sint, quos nisi esse? Sapiente, et natus incidunt explicabo, eveniet nesciunt exercitationem esse non velit magni dicta necessitatibus doloribus a facilis. Laborum, aliquam? Modi qui voluptatem iste minus, quas quae cupiditate recusandae aperiam, ut repellat ea at optio similique molestias quia. Amet ex debitis nulla doloribus quo animi adipisci aut tempora ratione ab. Quidem laborum at minima consequuntur delectus corrupti? Qui quaerat iure corrupti veniam ipsa neque nam unde incidunt, doloremque similique amet rem explicabo ullam, molestiae, doloribus ratione placeat at quae? Dicta quam tempora veniam aspernatur, temporibus illum esse, quo sint pariatur qui reprehenderit repellat optio, quaerat aliquam corporis? Ex officia, eius, minima vitae nam saepe dolorem impedit quod beatae error omnis exercitationem accusamus dignissimos quisquam quis commodi, qui voluptatibus alias deserunt! Quis, impedit qui molestias tempore perspiciatis harum dolorem officiis non eligendi recusandae autem, dolores iste quo. Esse quis eos cupiditate sunt, quaerat error pariatur nulla veniam ullam maiores laudantium possimus? Vel eveniet iste eos sequi tempore ad architecto nam dolore quae magnam, animi dolorum repudiandae, rem eligendi corporis harum voluptatem doloremque provident enim?
                    Aspernatur eligendi accusantium porro odio officia nam molestiae officiis autem quasi, aliquam iusto dolorem nihil dignissimos nobis ducimus earum cum. Quas, delectus? Odit veritatis placeat dolorem, aliquam, quasi debitis voluptatibus magnam nostrum ipsam rem quis dolores sunt. Tempore ad assumenda expedita adipisci? Facilis molestiae facere, eos vel sunt sint praesentium veritatis. Enim deleniti quidem ab quisquam autem dolor soluta assumenda in, reiciendis corrupti doloremque sequi perspiciatis nostrum voluptates neque velit, provident fugiat aliquid fugit quam officia quasi minima vitae? Tenetur, natus est. Deleniti?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, amet distinctio veniam, similique laboriosam totam facere quis debitis magnam dolores, numquam voluptatem possimus rem laudantium rerum nisi in non? Impedit neque nihil atque sapiente molestias qui dicta assumenda necessitatibus, iste officiis, sint, quos nisi esse? Sapiente, et natus incidunt explicabo, eveniet nesciunt exercitationem esse non velit magni dicta necessitatibus doloribus a facilis. Laborum, aliquam? Modi qui voluptatem iste minus, quas quae cupiditate recusandae aperiam, ut repellat ea at optio similique molestias quia. Amet ex debitis nulla doloribus quo animi adipisci aut tempora ratione ab. Quidem laborum at minima consequuntur delectus corrupti? Qui quaerat iure corrupti veniam ipsa neque nam unde incidunt, doloremque similique amet rem explicabo ullam, molestiae, doloribus ratione placeat at quae? Dicta quam tempora veniam aspernatur, temporibus illum esse, quo sint pariatur qui reprehenderit repellat optio, quaerat aliquam corporis? Ex officia, eius, minima vitae nam saepe dolorem impedit quod beatae error omnis exercitationem accusamus dignissimos quisquam quis commodi, qui voluptatibus alias deserunt! Quis, impedit qui molestias tempore perspiciatis harum dolorem officiis non eligendi recusandae autem, dolores iste quo. Esse quis eos cupiditate sunt, quaerat error pariatur nulla veniam ullam maiores laudantium possimus? Vel eveniet iste eos sequi tempore ad architecto nam dolore quae magnam, animi dolorum repudiandae, rem eligendi corporis harum voluptatem doloremque provident enim?
                    Aspernatur eligendi accusantium porro odio officia nam molestiae officiis autem quasi, aliquam iusto dolorem nihil dignissimos nobis ducimus earum cum. Quas, delectus? Odit veritatis placeat dolorem, aliquam, quasi debitis voluptatibus magnam nostrum ipsam rem quis dolores sunt. Tempore ad assumenda expedita adipisci? Facilis molestiae facere, eos vel sunt sint praesentium veritatis. Enim deleniti quidem ab quisquam autem dolor soluta assumenda in, reiciendis corrupti doloremque sequi perspiciatis nostrum voluptates neque velit, provident fugiat aliquid fugit quam officia quasi minima vitae? Tenetur, natus est. Deleniti?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, amet distinctio veniam, similique laboriosam totam facere quis debitis magnam dolores, numquam voluptatem possimus rem laudantium rerum nisi in non? Impedit neque nihil atque sapiente molestias qui dicta assumenda necessitatibus, iste officiis, sint, quos nisi esse? Sapiente, et natus incidunt explicabo, eveniet nesciunt exercitationem esse non velit magni dicta necessitatibus doloribus a facilis. Laborum, aliquam? Modi qui voluptatem iste minus, quas quae cupiditate recusandae aperiam, ut repellat ea at optio similique molestias quia. Amet ex debitis nulla doloribus quo animi adipisci aut tempora ratione ab. Quidem laborum at minima consequuntur delectus corrupti? Qui quaerat iure corrupti veniam ipsa neque nam unde incidunt, doloremque similique amet rem explicabo ullam, molestiae, doloribus ratione placeat at quae? Dicta quam tempora veniam aspernatur, temporibus illum esse, quo sint pariatur qui reprehenderit repellat optio, quaerat aliquam corporis? Ex officia, eius, minima vitae nam saepe dolorem impedit quod beatae error omnis exercitationem accusamus dignissimos quisquam quis commodi, qui voluptatibus alias deserunt! Quis, impedit qui molestias tempore perspiciatis harum dolorem officiis non eligendi recusandae autem, dolores iste quo. Esse quis eos cupiditate sunt, quaerat error pariatur nulla veniam ullam maiores laudantium possimus? Vel eveniet iste eos sequi tempore ad architecto nam dolore quae magnam, animi dolorum repudiandae, rem eligendi corporis harum voluptatem doloremque provident enim?
                    Aspernatur eligendi accusantium porro odio officia nam molestiae officiis autem quasi, aliquam iusto dolorem nihil dignissimos nobis ducimus earum cum. Quas, delectus? Odit veritatis placeat dolorem, aliquam, quasi debitis voluptatibus magnam nostrum ipsam rem quis dolores sunt. Tempore ad assumenda expedita adipisci? Facilis molestiae facere, eos vel sunt sint praesentium veritatis. Enim deleniti quidem ab quisquam autem dolor soluta assumenda in, reiciendis corrupti doloremque sequi perspiciatis nostrum voluptates neque velit, provident fugiat aliquid fugit quam officia quasi minima vitae? Tenetur, natus est. Deleniti?</p>

            </div>
        </div>
    )
}

export default Home